#!/usr/bin/env node
/**
 * Style Dictionary build: one DTCG source of truth (tokens/**) -> four platforms.
 *
 *   web      src/tokens/tokens.css          CSS custom properties, consumed by the app
 *   ts       src/tokens/tokens.generated.ts typed constants, a build-time artifact
 *   ios      build/tokens/Tokens.swift      demo only — proves cross-platform parity
 *   android  build/tokens/tokens.xml        demo only
 *
 * The color.wada.* primitives are reference-only: they exist so semantic tokens
 * can point at them, but they are filtered out of every emitted output so :root
 * stays exactly the hand-written set of names (--shell-*, --color-*, --radius-*).
 */
import StyleDictionary from 'style-dictionary'

/** primitives are for resolution only, never emitted */
const notPrimitive = (token) => !(token.path[0] === 'color' && token.path[1] === 'wada')

const DO_NOT_EDIT = [
  'AUTO-GENERATED by Style Dictionary — do not edit.',
  'Source: the tokens directory. Regenerate with `npm run build:tokens`.',
]

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  hooks: {
    fileHeaders: {
      'do-not-edit': () => DO_NOT_EDIT,
    },
  },
  platforms: {
    web: {
      transformGroup: 'css',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          filter: notPrimitive,
          options: { fileHeader: 'do-not-edit', outputReferences: false },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'tokens.generated.ts',
          format: 'javascript/es6',
          filter: notPrimitive,
          options: { fileHeader: 'do-not-edit' },
        },
      ],
    },
    ios: {
      transformGroup: 'ios-swift',
      buildPath: 'build/tokens/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'ios-swift/enum.swift',
          filter: notPrimitive,
          options: { fileHeader: 'do-not-edit', className: 'NejaTokens' },
        },
      ],
    },
    android: {
      transformGroup: 'android',
      buildPath: 'build/tokens/',
      files: [
        {
          destination: 'tokens.xml',
          format: 'android/resources',
          filter: notPrimitive,
          options: { fileHeader: 'do-not-edit' },
        },
      ],
    },
  },
})

await sd.hasInitialized
await sd.buildAllPlatforms()
console.log('✓ style-dictionary built web, ts, ios, android')
