/**
 * AUTO-GENERATED by Style Dictionary — do not edit.
 * Source: the tokens directory. Regenerate with `npm run build:tokens`.
 */

export const ColorBackground = "#eb5324";
export const ColorSurface = "#00978d";
export const ColorText = "#051230";
export const ColorTextMuted = "#051230";
export const ColorPrimary = "#00978d";
export const ColorPrimaryForeground = "#051230";
export const ColorSecondary = "#00978d";
export const ColorSecondaryForeground = "#051230";
export const ColorAccent = "#00978d";
export const ColorBorder = "#00978d";
export const RadiusSm = "2px";
export const RadiusMd = "4px";
export const RadiusLg = "10px";
export const ShellInk = "#051230";
export const ShellPaper = "#ebd3a2";
export const ShellEcru = "#c2ae93";
export const ShellSeal = "#eb5324";
export const ShellJade = "#00978d";
export const ShellSlate = "#34454c";
